export const LOGIN_SUCESS = 'LOGIN_SUCCESS'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOAD_PROFILE = 'LOAD_PROFILE'
export const LOGOUT = 'LOGOUT'
