export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST'
export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS'
export const HOME_VIDEOS_FAIL = 'HOME_VIDEOS_FAIL' 


export const SEARCH_VIDEO_REQUEST = 'SEARCH_VIDEO_REQUEST'
export const SEARCH_VIDEO_SUCCESS = 'SEARCH_VIDEO_SUCCESS'
export const SEARCH_VIDEO_FAIL = 'SEARCH_VIDEO_FAIL'
export const DISCARD_VIDEOS = 'DISCARD_VIDEOS'

export const SHOW_COMMENTS_REQUEST = 'SHOW_COMMENTS_REQUEST'
export const SHOW_COMMENTS_SUCCESS = 'SHOW_COMMENTS_SUCCESS'
export const SHOW_COMMENTS_FAIL = 'SHOW_COMMENTS_FAIL'

export const VIDEO_DETAILS_REQUEST = 'VIDEO_DETAILS_REQUEST'
export const VIDEO_DETAILS_SUCCESS = 'VIDEO_DETAILS_SUCCESS'
export const VIDEO_DETAILS_FAIL = 'VIDEO_DETAILS_FAIL'

export const CHANNEL_DETAILS_REQUEST = 'CHANNEL_DETAILS_REQUEST'
export const CHANNEL_DETAILS_SUCCESS = 'CHANNEL_DETAILS_SUCCESS'
export const CHANNEL_DETAILS_FAIL = 'CHANNEL_DETAILS_FAIL'

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS'
export const ADD_COMMENT_FAIL = 'ADD_COMMENT_FAIL'

export const RELATED_VIDEOS_REQUEST = 'RELATED_VIDEOS_REQUEST'
export const RELATED_VIDEOS_SUCCESS = 'RELATED_VIDEOS_SUCCESS'
export const RELATED_VIDEOS_FAIL = 'RELATED_VIDEOS_FAIL'

export const DISCARD_COMMENTS = 'DISCARD_COMMENTS'